ALTER TABLE candidaturas_fornecedores
  ADD COLUMN IF NOT EXISTS notif_24h_em  TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS notif_12h_em  TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS notif_6h_em   TIMESTAMPTZ;
